package engine

type MarianSaint struct {
	Name    string `json:"name"`
	Feast   string `json:"feast"`
	Context string `json:"context"`
}

var MarianSaints = []MarianSaint{
	{Name: "S. Afonso Maria de Liguori", Feast: "2/ago", Context: "Bispo e Doutor da Igreja. Fundador dos Missionários Redentoristas, grande incentivador das CC.MM. Congregado em Nápoles, Itália."},
	{Name: "S. Afonso Rodrigues", Feast: "30/out", Context: "Confessor e Religioso (jesuíta). Diretor de CM na ilha de Maiorca, Espanha."},
	{Name: "S. Alberto Hurtado", Feast: "18/ago", Context: "Confessor e Religioso (jesuíta). Congregado do Colégio dos Jesuítas em Santiago, Chile. Diretor da CM."},
	{Name: "S. Ana Maria de Jesus de Paredes", Feast: "2/jun", Context: "Virgem. Congregada na Igreja dos Jesuítas em Quito, Equador. Chamada a 'Açucena de Quito'."},
	{Name: "B. Anacleto González Flores", Feast: "20/nov", Context: "Mártir Cristero, líder da Revolução Cristera. Congregado na Congregação Mariana do Santuário San José de Gracia, em Guadalajara."},
	{Name: "S. André Bobola", Feast: "16/mai", Context: "Mártir na Bielo-Rússia. Congregado no Colégio dos Jesuítas em Vilna, na Lituânia."},
	{Name: "S. André Kim", Feast: "16/set", Context: "Mártir na Coréia. Congregado Mariano em Macau, China."},
	{Name: "S. Antonio Daniel", Feast: "19/out", Context: "Mártir no Canadá. Congregado no seminário dos jesuítas, na França."},
	{Name: "B. Antonio Baldinucci", Feast: "7/nov", Context: "Confessor. Congregado no Colégio dos Jesuítas em Florença, Itália."},
	{Name: "S. Antônio Maria Claret", Feast: "23/out", Context: "Bispo e confessor. Fundador dos Padres Claretianos, grande incentivador das CC.MM. e chamado o 'restaurador moderno das CCMM'."},
	{Name: "B. Antonio Ixida", Feast: "3/set", Context: "Mártir no Japão e sacerdote (jesuíta). Congregado na Missão dos Jesuítas em Arima, Japão."},
	{Name: "B. Baltazar de Torres", Feast: "20/jun", Context: "Mártir no Japão e sacerdote (jesuíta). Congregado no Colégio dos Jesuítas em Toledo, Espanha."},
	{Name: "S. Bartolomea Capitanio", Feast: "26/jul", Context: "Virgem. Fundadora das Irmãs de Maria Menina. Congregada em Lovere, Itália."},
	{Name: "S. Bernadete Soubirous", Feast: "16/abr", Context: "Virgem. Vidente de Nossa Senhora de Lourdes. Congregada em Lourdes, França."},
	{Name: "S. Bernardino Realino", Feast: "3/jul", Context: "Confessor e sacerdote (jesuíta), apóstolo da cidade de Lecce na Itália onde fundou e dirigiu várias Congregações Marianas."},
	{Name: "S. Catarina Tekakwita", Feast: "17/abr", Context: "Virgem. Indígena, Congregada na Missão de Sault, Canadá. Chamada o 'Lírio dos Iroqueses'."},
	{Name: "B. Camilo Costanzo", Feast: "15/set", Context: "Mártir no Japão e sacerdote (jesuíta). Congregado no Colégio dos Jesuítas de Nápoles, Itália."},
	{Name: "S. Camilo de Lellis", Feast: "18/jul", Context: "Sacerdote diocesano, fundador da Congregação dos Ministros dos Enfermos, inspirado no trabalho dos Congregados de Roma."},
	{Name: "S. Carlos Borromeu", Feast: "4/nov", Context: "Cardeal-Arcebispo de Milão. Fundador de várias CC.MM., sobretudo nos Colégios de sua Diocese."},
	{Name: "S. Carlos de Sezze", Feast: "6/jan", Context: "Confessor e Religioso (Franciscano). Congregado no Colégio dos Jesuítas em Sezze, Itália."},
	{Name: "S. Carlos Garnier", Feast: "26/set", Context: "Mártir no Canadá. Congregado no Colégio dos Jesuítas em Clermont-Ferrand, França."},
	{Name: "B. Carlos Lopez Vidal", Feast: "6/ago", Context: "Mártir durante a perseguição religiosa na Espanha. Morreu aos brados de 'Viva Cristo Rey'. Congregado em Valência, Espanha."},
	{Name: "B. Carlos Spínola", Feast: "10/set", Context: "Mártir no Japão e sacerdote (jesuíta). Congregado no Colégio dos Jesuítas em Nola, Itália."},
	{Name: "B. Charles-François Le Gué", Feast: "19/jan", Context: "Mártir na Revolução Francesa e sacerdote (jesuíta), Congregado no Colégio dos Jesuítas em Rodez, França."},
	{Name: "B. Claude-Antoine Raoul Laporte", Feast: "19/jan", Context: "Mártir na Revolução Francesa e sacerdote (jesuíta). Congregado e Diretor da CM do Colégio dos Jesuítas em Brest, França."},
	{Name: "B. Claude Cayx-Dumas", Feast: "19/jan", Context: "Mártir na Revolução Francesa e sacerdote (jesuíta). Congregado no Colégio dos Jesuítas de Carcassone, França."},
	{Name: "S. Cláudio de La Colombière", Feast: "15/fev", Context: "Diretor espiritual de Santa Margarida Maria, apóstolo da devoção ao Coração de Jesus. Diretor da CM de Lyon e depois de Paray-le-Monial."},
	{Name: "S. Conrado de Parzham", Feast: "21/abr", Context: "Confessor e religioso (capuchinho). Congregado em Altötting, Alemanha."},
	{Name: "S. Crispim de Viterbo", Feast: "19/mai", Context: "Confessor e Religioso (Capuchinho). Congregado em Viterbo, Itália."},
	{Name: "B. Diogo Aloisio de San Vitores", Feast: "6/out", Context: "Mártir nas Ilhas Marianas, Oceania. Congregado no Colégio dos Jesuítas em Burgos, Espanha."},
	{Name: "B. Diogo Carvalho", Feast: "7/jul", Context: "Mártir no Japão e sacerdote (jesuíta). Congregado no Colégio dos Jesuítas de Coimbra, Portugal."},
	{Name: "S. Edmundo Campion", Feast: "1/dez", Context: "Mártir na Inglaterra e sacerdote. Congregado e depois Diretor da CM no Colégio dos Jesuítas em Praga na Boêmia."},
	{Name: "S. Estanislau Kostka", Feast: "13/nov", Context: "Confessor. Congregado no Colégio dos Jesuítas em Viena, Áustria, onde se sentiu chamado à vida religiosa pela Virgem Maria."},
	{Name: "S. Estêvão Pongracz", Feast: "7/set", Context: "Mártir na Hungria e sacerdote (jesuíta). Congregado no Colégio dos Jesuítas em Viena, Áustria."},
	{Name: "S. Felipe de Jesus", Feast: "5/fev", Context: "Mártir no Japão. Congregado no Colégio dos Jesuítas no México."},
	{Name: "S. Felipe Evans", Feast: "22/jul", Context: "Mártir na Inglaterra e sacerdote (jesuíta). Congregado no Colégio dos Jesuítas em Saint-Omer, França."},
	{Name: "S. Fidélis de Sigmaringa", Feast: "24/abr", Context: "Protomártir da Propaganda Fidei na Suíça e religioso (capuchinho). Congregado no Colégio dos Jesuítas em Friburgo, Suíça."},
	{Name: "S. Francisca Xavier Cabrini", Feast: "13/nov", Context: "Virgem e fundadora das Missionárias do Sagrado Coração de Jesus. Congregada em Santo Angelo Lodigiano, Itália."},
	{Name: "S. Francisco de Borgia", Feast: "10/out", Context: "3º Superior Geral da Companhia de Jesus, grande promotor das CC.MM."},
	{Name: "S. Francisco de Geronimo", Feast: "2/jul", Context: "Confessor. Congregado no Colégio dos Jesuítas em Taranto, Itália e fundador de muitas CC.MM."},
	{Name: "S. Francisco de Sales", Feast: "29/jan", Context: "Doutor da Igreja. Arcebispo de Genebra. Congregado no Colégio dos Jesuítas em Clermont-Ferrand, França, promotor das CC.MM na sua diocese."},
	{Name: "B. Francisco Jacinto Le Livec", Feast: "19/jan", Context: "Mártir na Revolução Francesa e sacerdote (jesuíta). Congregado e Diretor da CM do Colégio dos Jesuítas em Vannes, França."},
	{Name: "S. Francisco Solano", Feast: "14/jul", Context: "Confessor e religioso (franciscano). Missionário no Peru. Congregado em Montilla, na Espanha."},
	{Name: "S. Gabriel da Virgem Dolorosa", Feast: "27/fev", Context: "Confessor e Religioso (passionista). Congregado no Colégio dos Jesuítas de Spoleto, Itália."},
	{Name: "S. Gabriel Lallemand", Feast: "19/out", Context: "Mártir no Canadá e sacerdote. Congregado no Colégio dos Jesuítas em Paris, França."},
	{Name: "S. Gaspar del Búfalo", Feast: "28/dez", Context: "Confessor e sacerdote. Fundador da Congregação do Preciosíssimo Sangue. Congregado no Colégio Romano em Roma."},
	{Name: "S. Gaspar Luiz Bertoni", Feast: "12/jun", Context: "Fundador dos Padres dos Sagrados Estigmas, apóstolo da juventude. Congregado em Verona, Itália."},
	{Name: "B. Guilherme Harcourt", Feast: "1/dez", Context: "Mártir na Inglaterra em 1679 e sacerdote (jesuíta), Congregado no Colégio dos Jesuítas em Saint-Omer, França."},
	{Name: "S. Gregório Barbarigo", Feast: "17/jun", Context: "Bispo e confessor. Congregado no Colégio dos Jesuítas em Roma."},
	{Name: "B. Grimoaldo Santamaria", Feast: "18/nov", Context: "Confessor e religioso (passionista). Congregado em Ceccano, Itália."},
	{Name: "B. Inocêncio XI", Feast: "12/ago", Context: "Papa. Congregado no Colégio dos Jesuítas em Como, Itália. Grande protetor e incentivador das CCMM."},
	{Name: "S. Isaac Jogues", Feast: "19/out", Context: "Mártir no Canadá. Congregado no Colégio dos Jesuítas em Orléans, França."},
	{Name: "B. João Batista Machado", Feast: "19/jan", Context: "Mártir no Japão e sacerdote (jesuíta). Congregado no Colégio dos Jesuítas em Coimbra, Portugal."},
	{Name: "B. João Batista Zola", Feast: "20/jun", Context: "Mártir no Japão e sacerdote (jesuíta). Congregado no Colégio dos Jesuítas de Coimbra, Portugal."},
	{Name: "S. João Cornay", Feast: "24/nov", Context: "Mártir na Indochina e Missionário. Congregado no Colégio de Montmorillon dos Jesuítas na França."},
	{Name: "B. João Cornelis", Feast: "1/dez", Context: "Mártir na Inglaterra e sacerdote (jesuíta). Congregado no Colégio do Ingleses em Roma."},
	{Name: "B. João Gavan", Feast: "1/dez", Context: "Mártir na Inglaterra e sacerdote. Congregado no Colégio dos Jesuítas em Douai, França."},
	{Name: "S. João Luís Bonnard", Feast: "24/nov", Context: "Mártir na Indochina e sacerdote. Congregado no Seminário de Saint Jotard, França."},
	{Name: "B. João Juvenal Ancina", Feast: "30/ago", Context: "Bispo e Confessor. Congregado no Colégio dos Jesuítas em Turim, Itália."},
	{Name: "S. João Teófanes Venard", Feast: "24/nov", Context: "Mártir na Indochina. Congregado no Colégio dos Jesuítas em Paris, França."},
	{Name: "S. João Ogilvie", Feast: "10/mar", Context: "Mártir na Escócia. Congregado no Colégio dos Jesuítas em Olmutz, Lovaina, Bélgica."},
	{Name: "S. João Batista de la Salle", Feast: "15/mai", Context: "Confessor, educador da juventude, fundador dos Irmãos Lassalistas. Congregado no Colégio dos Jesuítas em Reims, França."},
	{Name: "S. João Batista de Rossi", Feast: "23/mai", Context: "Confessor e sacerdote. Congregado no Colégio Romano em Roma."},
	{Name: "S. João Berchmans", Feast: "26/nov", Context: "Confessor e seminarista. Congregado no Colégio dos Jesuítas em Malinas, Bélgica. Padroeiro dos coroinhas."},
	{Name: "S. João de Brébeuf", Feast: "19/out", Context: "Mártir no Canadá. Congregado no Colégio dos Jesuítas em Bayeux, França."},
	{Name: "S. João de Brito", Feast: "4/fev", Context: "Mártir na Índia e sacerdote. Congregado no Colégio dos Jesuítas em Lisboa, Portugal."},
	{Name: "S. João de la Lande", Feast: "19/out", Context: "Mártir no Canadá. Congregado na França."},
	{Name: "S. João Eudes", Feast: "19/ago", Context: "Confessor e sacerdote, fundador de Congregações Religiosas. Congregado no Colégio dos Jesuítas em Caen, França."},
	{Name: "S. João Francisco de Régis", Feast: "16/jun", Context: "Confessor e missionário. Congregado no Colégio dos Jesuítas em Beziers, França."},
	{Name: "S. João Macias", Feast: "18/set", Context: "Confessor e missionário no Peru. Congregado na Espanha."},
	{Name: "S. João Paulo II", Feast: "22/out", Context: "Papa e congregado mariano."},
	{Name: "S. João Sarkander", Feast: "26/jul", Context: "Mártir na Eslováquia pelo segredo da Confissão. Congregado no Colégio dos Jesuítas em Praga, Boêmia."},
	{Name: "S. Josafá Kuncewycz", Feast: "12/nov", Context: "Mártir na Ucrânia. Congregado no Colégio dos Jesuítas em Vilna na Lituânia."},
	{Name: "S. José Cafasso", Feast: "23/jun", Context: "Confessor e sacerdote, apóstolo dos doentes e formador de sacerdotes. Congregado em Chieri, Itália."},
	{Name: "S. José Calazans", Feast: "25/ago", Context: "Confessor, sacerdote, fundador dos Clérigos Regulares das Escolas Pias. Congregado como estudante em Roma."},
	{Name: "S. José Maria Pignatelli", Feast: "15/nov", Context: "Confessor. Sustentou a fidelidade de seus irmãos durante a supressão da Companhia de Jesus. Congregado no Colégio dos Jesuítas em Zaragoza, Espanha."},
	{Name: "S. José de Anchieta", Feast: "9/jun", Context: "Confessor. O 'Apóstolo do Brasil', fundador das primeiras CCMM do Brasil nos colégios da Bahia e do RJ."},
	{Name: "S. José Maria Rubio", Feast: "4/mai", Context: "Confessor e Religioso (jesuíta). Congregado do Sem. de Alméria, Espanha, apóstolo de Madrid."},
	{Name: "S. Joaquina de Vedruna", Feast: "22/mai", Context: "Santa Mulher, fundadora das Carmelitas da Caridade, promotora das CC.MM."},
	{Name: "B. Julião Maunoir", Feast: "28/jan", Context: "Confessor e sacerdote (jesuíta). Congregado no Colégio dos Jesuítas em Rennes, França."},
	{Name: "B. Ladislao Findysz", Feast: "21/ago", Context: "Mártir sob o regime comunista na Polônia. Congregado no Colégio de Krościenko Niżne."},
	{Name: "S. Leonardo de Porto Maurício", Feast: "26/nov", Context: "Confessor e religioso (capuchinho). Congregado na Prima Primaria de Roma, grande missionário popular."},
	{Name: "B. Leonardo Pérez Larios", Feast: "2/jun", Context: "Mártir Cristero no México. Congregado na Congregação Mariana da Imaculada Conceição em León, México."},
	{Name: "S. Luís Gonzaga", Feast: "21/jun", Context: "Confessor, declarado pela Igreja 'Padroeiro da Juventude'. Congregado em Roma, Itália."},
	{Name: "S. Luís Maria Grignion de Montfort", Feast: "28/abr", Context: "Confessor, fundador de Congregações, grande devoto da Virgem Maria e autor do Tratado da Verdadeira Devoção. Congregado no Colégio de Rennes, França."},
	{Name: "S. Luís Orione", Feast: "12/mar", Context: "Confessor, fundador dos Orionitas, grande incentivador das CC.MM."},
	{Name: "S. Magdalena Sofia Barat", Feast: "25/mar", Context: "Santa Mulher, fundadora do Sagrado Coração, promotora das CC.MM."},
	{Name: "S. Maria Rosa Júlia Billiart", Feast: "8/abr", Context: "Virgem. Congregada em Zuster, Bélgica. Fundadora das Filhas de Nossa Senhora de Namur."},
	{Name: "B. Maria Teresa Ledóchowska", Feast: "6/jul", Context: "Virgem. Congregada no Colégio de Sankt-Pölten, Áustria, fundadora do Inst. de S. Pedro Claver."},
	{Name: "B. Maria Teresa Soubiran de la Louvière", Feast: "7/jun", Context: "Religiosa. Congregada em Castelnaudary, França, onde lançou as bases da CM Auxiliadora."},
	{Name: "S. Marcos Crisino", Feast: "7/set", Context: "Mártir na Hungria e sacerdote. Congregado no Colégio dos Jesuítas em Graz, Áustria."},
	{Name: "S. Melchior Grodecz", Feast: "7/set", Context: "Mártir na Hungria e sacerdote (jesuíta). Congregado no Colégio dos Jesuítas em Viena, Áustria."},
	{Name: "B. Miguel Agostinho Pro", Feast: "23/nov", Context: "Mártir Cristero no México e sacerdote (jesuíta). Congregado no Colégio dos Jesuítas no México."},
	{Name: "B. Miguel de Carvalho", Feast: "25/ago", Context: "Mártir no Japão e sacerdote (jesuíta). Congregado em Coimbra, Portugal."},
	{Name: "B. Miguel Gómez Loza", Feast: "21/mar", Context: "Mártir Cristero no México, leigo e líder da Resistência. Congregado na CM de San José."},
	{Name: "S. Natal Chabanel", Feast: "26/set", Context: "Mártir no Canadá e sacerdote. Congregado no Colégio dos Jesuítas em Rodez, França."},
	{Name: "S. Paulina do Coração Agonizante de Jesus", Feast: "9/jul", Context: "Virgem. Fundadora das Irmãzinhas da Imaculada Conceição. Congregada em Vigolo, Nova Trento, SC, Brasil."},
	{Name: "B. Paulo Navarro", Feast: "19/jan", Context: "Mártir no Japão e sacerdote (jesuíta). Congregado em Nápoles, Itália."},
	{Name: "S. Paulo Chong Hasang", Feast: "22/set", Context: "Mártir na Coreia. Congregado em Macau, China."},
	{Name: "B. Pedro Berna", Feast: "15/jul", Context: "Mártir na Índia em 1583. Congregado no Colégio Romano, em Roma."},
	{Name: "S. Pedro Canísio", Feast: "21/dez", Context: "Doutor da Igreja, segundo Apóstolo da Alemanha, fundador de inúmeras CC.MM."},
	{Name: "S. Pedro Chanel", Feast: "28/abr", Context: "Mártir na Polinésia em 1841. Congregado no Colégio de Saint-Maximien, França."},
	{Name: "S. Pedro Claver", Feast: "9/set", Context: "Missionário na Colômbia, declarado 'Apóstolo dos Negros' e padroeiro das Missões. Congregado em Barcelona, Espanha."},
	{Name: "S. Pedro Fabro", Feast: "1/ago", Context: "Primeiro sacerdote da Companhia de Jesus, organizador do grupo de leigos precursor das CC.MM."},
	{Name: "S. Pedro Fourier", Feast: "9/dez", Context: "Confessor e educador da juventude. Congregado em Pont-à-Mousson, França."},
	{Name: "S. Pedro Julião Eymard", Feast: "2/ago", Context: "Confessor, apóstolo da Eucaristia, fundador dos Padres Sacramentinos. Congregado em Mure d'Ysère, França."},
	{Name: "S. Pedro Dumoulin-Borie", Feast: "24/nov", Context: "Mártir na Indochina em 1838. Congregado no Seminário Diocesano na França."},
	{Name: "S. Pier-giorgio Frassati", Feast: "4/jul", Context: "Confessor e leigo. Congregado no Instituto Social dos Jesuítas em Turim, Itália."},
	{Name: "B. Pio IX", Feast: "7/fev", Context: "Papa. Congregado na Prima-Primária em Roma, Itália. Defensor do Dogma da Imaculada Conceição."},
	{Name: "S. Renato Goupil", Feast: "19/out", Context: "Mártir no Canadá em 1642. Congregado na França."},
	{Name: "B. Renato Maria Andrieux", Feast: "19/jan", Context: "Mártir na Revolução Francesa e sacerdote (jesuíta). Congregado no Colégio dos Jesuítas em Paris, França."},
	{Name: "B. Roberto Johnson", Feast: "28/mai", Context: "Mártir na Inglaterra. Congregado no Colégio dos Ingleses em Roma."},
	{Name: "S. Roberto Southwell", Feast: "20/fev", Context: "Mártir na Inglaterra e Congregado no Colégio dos Jesuítas em Douai, França."},
	{Name: "B. Rodolfo Acquaviva", Feast: "25/jul", Context: "Mártir na Índia. Congregado e Diretor da CM do Colégio Germânico em Roma."},
	{Name: "B. Ruperto Mayer", Feast: "1/nov", Context: "Confessor. Diretor da CM de Munique, Alemanha. Opositor heróico do nazismo."},
	{Name: "B. Salvio Huix Miralpéix", Feast: "6/nov", Context: "Bispo e Mártir. Congregado Mariano em Vich, na Espanha."},
	{Name: "S. Teresa do Menino Jesus", Feast: "3/out", Context: "Virgem e religiosa (carmelita). Padroeira das missões e Doutora da Igreja. Congregada na Abadia de Alençon, França."},
	{Name: "B. Tiago Salès", Feast: "19/jan", Context: "Mártir da Eucaristia na França e sacerdote (jesuíta). Congregado no Colégio de Bellon, França."},
	{Name: "B. Tomas Holland", Feast: "12/dez", Context: "Mártir na Inglaterra e sacerdote (jesuíta). Congregado e Diretor da CM em Dijon, França."},
	{Name: "S. Úrsula Ledóchowska", Feast: "29/mai", Context: "Religiosa e Fundadora. Congregada em Estocolmo, na Suécia."},
	{Name: "B. Vicente José Le Rousseau", Feast: "19/jan", Context: "Mártir na Revolução Francesa. Congregado em Consecoat, França."},
	{Name: "S. Vicente de Paulo", Feast: "19/jul", Context: "Confessor, fundador dos Lazaristas e das Filhas da Caridade. Congregado em Toulouse, França."},
	{Name: "S. Vicente Maria Strambi", Feast: "1/jan", Context: "Bispo e confessor, passionista. Congregado em Roma, Itália."},
	{Name: "S. Vicente Pallotti", Feast: "22/jan", Context: "Confessor e sacerdote, fundador do Apostolado Católico. Congregado no Colégio Romano em Roma."},
	{Name: "S. Vincenza Geroza", Feast: "28/jun", Context: "Religiosa, companheira de Santa Bartolomea Capitanio. Congregada em Lovere, Itália."},
}
